import type { Metadata } from "next";
import "./globals.css";
import "@/styles/global.scss";
import { helveticaLight, helveticaRoman } from "@/fonts";
import Header from "@/components/organisms/Header";

export const metadata: Metadata = {
  title: "Tuan Ng",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${helveticaRoman.variable} ${helveticaLight.variable}`}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
